$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: iris-pkl-inference-env
version: 1

image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference:latest

conda_file:
  channels:
    - conda-forge
  dependencies:
    - python=3.9
    - pip
    - pip:
        - scikit-learn==1.5.2
        - joblib==1.4.2
